name: Publish Dev Branch to TestPyPI
on:
  push:
    branches: ["dev"]

jobs:
  test-pypi-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: TestPyPI
      url: https://test.pypi.org/project/apix-core
    permissions:
      id-token: write

    steps:

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Poetry and build package
      run: |
        pip install poetry
        poetry build

    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
